basePath: /
host: localhost:8080
info:
  contact:
    email: support@jalurberlian.id
    name: API Support
    url: http://www.jalurberlian.id/support
  description: Real-time fleet management and order tracking system for PT. Jalur
    Berlian Makassar
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Jalur Berlian Fleet Management API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
