ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS origin_lat  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS origin_lng  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS dest_lat    DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS dest_lng    DOUBLE PRECISION;
