package model

import "time"

// Customer stores business customer information without authentication credentials.
type Customer struct {
	ID          int       `db:"id" json:"id"` // Immutable: Auto-generated by database
	CompanyName string    `db:"company_name" json:"company_name" example:"PT. Nusantara Logistik"`
	PICName     string    `db:"pic_name" json:"pic_name" example:"Budi Santoso"`
	Phone       string    `db:"phone" json:"phone" example:"+628123456789"`
	Email       string    `db:"email" json:"email" example:"budi@nusantara.co.id"`
	Address     string    `db:"address" json:"address" example:"Jl. Sudirman No. 123, Jakarta"`
	NPWP        string    `db:"npwp" json:"npwp" example:"01.234.567.8-901.000"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"` // Immutable: Auto-set by database
}

// CreateCustomerRequest is the request DTO for creating a new customer.
type CreateCustomerRequest struct {
	CompanyName string `json:"company_name" example:"PT. Nusantara Logistik" binding:"required"`
	PICName     string `json:"pic_name" example:"Budi Santoso" binding:"required"`
	Phone       string `json:"phone" example:"+628123456789" binding:"required"`
	Email       string `json:"email" example:"budi@nusantara.co.id"`
	Address     string `json:"address" example:"Jl. Sudirman No. 123, Jakarta"`
	NPWP        string `json:"npwp" example:"01.234.567.8-901.000"`
}

// UpdateCustomerRequest is the request DTO for updating a customer (partial update).
type UpdateCustomerRequest struct {
	CompanyName *string `json:"company_name" example:"PT. Nusantara Logistik"`
	PICName     *string `json:"pic_name" example:"Budi Santoso"`
	Phone       *string `json:"phone" example:"+628123456789"`
	Email       *string `json:"email" example:"budi@nusantara.co.id"`
	Address     *string `json:"address" example:"Jl. Sudirman No. 123, Jakarta"`
	NPWP        *string `json:"npwp" example:"01.234.567.8-901.000"`
}
